### ISSUE TITLE
Small typo in LNodeType.ocl

### ISSUE THREAD

**Issue by pascalwilbrink** [riseclipse/riseclipse-ocl-constraints-scl2003#100]
There's a small typo in the LNodeType.ocl Rule.
probably some copy/paste issue.

I'll open a PR for this :)
https://github.com/riseclipse/riseclipse-ocl-constraints-scl2003/blob/94679bc920360dfaf90d3a15b25365da98c65df1/fr.centralesupelec.edf.riseclipse.iec61850.scl.ocl/RequiredElements/LNodeType.ocl#L26C1-L39C1

**Comment by ADehouck** [comment]
Thank you @pascalwilbrink !
