### ISSUE TITLE
New constraint to add: Check for mandatory elements in GSE address (according to IEC 61850-8-1 Ed 2.1)

### ISSUE THREAD

**Issue by bruder-sisco** [riseclipse/riseclipse-ocl-constraints-scl2003#57]
Thanks for reporting an issue! 

I'm submitting a ... 
-------------------------------------------
[ ] bug report [x ] New constraint to add

Describe your issue here
-------------------------------------------
IEC 61850-8-1 Ed 2.1, section 25.3.2 says that the following "P" elements are mandatory in GSE for L2 GOOSE.
`        <GSE ldInst="SISCO1" cbName="gcb1">
          <Address>
            <P type="APPID">00</P>
            <P type="VLAN-ID">0</P>
            <P type="VLAN-PRIORITY">4</P>
            <P type="MAC-Address">01-0C-CD-01-00-00</P>
          </Address>
        </GSE>`

NOTE: This is only for L2 GOOSE, so you would also have to find the matching GSEControl to know if this is a L2 GOOSE address (there are different rules for R-GOOSE addressing).

What are the steps to reproduce this issue?
-------------------------------------------
1. There is no error if these "P" elements are missing.
2. The "P" element is optional, so the SCL Schema cannot require any of these elements.
3. The "P" element also allows almost any value for the "type" attribute, so if any "type" value is misspelled. it would be ignored.

What happens?
-------------
No parse errors if a mandatory element is missing, but applications may use unexpected values.

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
…

Any other comments?
-------------------
It would be good to also check that there is only one element for each "P type". The SCL schema would allow multiple entries like this:
`            <P type="MAC-Address">01-0C-CD-01-00-00</P>
            <P type="MAC-Address">01-0C-CD-01-55-55</P>`
but this would be very confusing if someone accidentally enters this.

**Comment by bruder-sisco** [comment]
NOTE: I suspect it is difficult, or at least awkward, to find the matching GSEControl to see if it is L2 GOOSE or R-GOOSE (addressing requirements for R-GOOSE are much different). I wonder if it is worth proposing to IEC a different addressing element for R-GOOSE (e.g. RGSE) and similarly for R-SV (e.g. RSMV). This should be easier for many applications to manage. At the 2021 IOP, some SCD files had an L2 GOOSE address for R-GOOSE.

**Comment by ADehouck** [comment]
Precision : how do you determine that a GSEControl is a L2 GOOSE and not a R-GOOSE ?
Is it via the element “Protocol” in the GSEControl ?
If there is no element “Protocol” with the value “R-GOOSE”, can we consider that it is a L2 GOOSE ?

In IED section : example of GSEControl containing an element Protocol, with the value R-GOOSE :

`<GSEControl name="GoCB02" appID="GoCB02" datSet="CmdResv">`

> `<IEDName>AA1_D1_Q11A1</IEDName>`
`<IEDName>AA1_D1_Q10A1</IEDName>`
`<IEDName>AA1_D1_Q07A1</IEDName>`
`<Protocol mustUnderstand="true">R-GOOSE</Protocol>`

`</GSEControl>`

The rule would then be :

If a GSE refers to a GSEControl that does not contain <Protocol>R-GOOSE, then check that there is one and only one P element with type = APPID, VLAN_ID, VLAN-PRIORITY, MAC-Address

Is it correct ?

**Comment by bruder-sisco** [comment]
Yes, I think you understand it perfectly. The "Protocol" element with the value R-GOOSE indicates it is an R-GOOSE. If that is not present, it is an L2 GOOSE. So I think the rule you suggest is perfect, and very concise.

I will check later, but I seem to recall some users left the value empty, like this:
   <Protocol mustUnderstand="true"></Protocol>
and assumed it defaults to R-GOOSE. I don't even know if that is allowed, but if it is, it might be another case to handle later. Personally, I think that should not be allowed.

**Comment by bruder-sisco** [comment]
I found that "some" SCL files do indeed leave the Protocol element empty, like this:
"<Protocol mustUnderstand="true"></Protocol>"
and this means R-GOOSE because the XSD indicates a fixed value of "R-GOOSE".
 
This looks confusing, but the OCL should take this into account.  I think the rule could be:

If a GSE refers to a GSEControl that does not contain a Protocol element, then check that there is one and only one P element with type = APPID, VLAN_ID, VLAN-PRIORITY, MAC-Address

because the Protocol value is fixed as R-GOOSE.
