### ISSUE TITLE
Line number is missing in the error message: [OCL/SemanticConstraints/ConductingEquipment_number_of_Terminals]

### ISSUE THREAD

**Issue by ADehouck** [riseclipse/riseclipse-ocl-constraints-scl2003#76]
I'm submitting a ... 
-------------------------------------------
[X] bug report [ ] New constraint to add

Describe your issue here
-------------------------------------------
The line number is missing in the error message:
[OCL/SemanticConstraints/ConductingEquipment_number_of_Terminals] the number of Terminals in ConductingEquipment of type CTR is wrong

**Comment by marcadetd** [comment]
It is not missing
